DROP AUDIT POLICY audit_objpriv_txp;

CREATE AUDIT POLICY audit_objpriv_txp
ACTIONS delete on travelxp.affiliation,
        update on travelxp.affiliation,
        delete on travelxp.agent,
        update on travelxp.agent,
        delete on travelxp.applied_reward,
        update on travelxp.applied_reward,
        delete on travelxp.booking,
        update on travelxp.booking,
        delete on travelxp.class,
        update on travelxp.class,
        delete on travelxp.client,
        update on travelxp.client,
        delete on travelxp.commission,
        update on travelxp.commission,
        delete on travelxp.credit_card,
        update on travelxp.credit_card,
        delete on travelxp.destination,
        update on travelxp.destination,
        delete on travelxp.fee,
        update on travelxp.fee,
        delete on travelxp.payment,
        update on travelxp.payment,
        delete on travelxp.product,
        update on travelxp.product,
        delete on travelxp.product_supplier,
        update on travelxp.product_supplier,
        delete on travelxp.reward_card,
        update on travelxp.reward_card,
        delete on travelxp.supplier,
        update on travelxp.supplier,
        delete on travelxp.trip,
        update on travelxp.trip,
        delete on travelxp.trip_type,
        update on travelxp.trip_type;
        
      