DROP TABLESPACE data INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE adhoc INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE index_tbs INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE data
DATAFILE 'C:\CDB2\oradata\travelxp\data01.dbf' 
SIZE 5M REUSE AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE adhoc
DATAFILE 'C:\CDB2\oradata\travelxp\adhoc01.dbf'
SIZE 5M REUSE AUTOEXTEND ON NEXT 1M MAXSIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE index_tbs
DATAFILE 'C:\CDB2\oradata\travelxp\index01.dbf'
SIZE 2M REUSE AUTOEXTEND ON NEXT 500K MAXSIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

