DROP PROFILE agent_prof CASCADE;
DROP PROFILE manager_prof CASCADE;
DROP PROFILE owner_prof CASCADE;

ALTER SYSTEM SET RESOURCE_LIMIT=TRUE;

REM------------Create agent password profile ---------------

CREATE PROFILE agent_prof LIMIT
FAILED_LOGIN_ATTEMPTS    3
PASSWORD_LOCK_TIME       UNLIMITED
PASSWORD_LIFE_TIME       30
PASSWORD_REUSE_TIME      30
PASSWORD_REUSE_MAX       3
PASSWORD_GRACE_TIME      5
PASSWORD_VERIFY_FUNCTION DEFAULT
SESSIONS_PER_USER        1
IDLE_TIME                30;

REM------------ Create manager profile --------------------------

CREATE PROFILE manager_prof LIMIT
FAILED_LOGIN_ATTEMPTS    3
PASSWORD_LOCK_TIME       UNLIMITED
PASSWORD_LIFE_TIME       60
PASSWORD_REUSE_TIME      30
PASSWORD_REUSE_MAX       3
PASSWORD_GRACE_TIME      5
PASSWORD_VERIFY_FUNCTION DEFAULT
SESSIONS_PER_USER        1
IDLE_TIME                60;

REM------------ Create owner profile ----------------------------

CREATE PROFILE owner_prof LIMIT
FAILED_LOGIN_ATTEMPTS    3
PASSWORD_LOCK_TIME       UNLIMITED
PASSWORD_LIFE_TIME       180
PASSWORD_REUSE_TIME      30
PASSWORD_REUSE_MAX       3
PASSWORD_GRACE_TIME      14
PASSWORD_VERIFY_FUNCTION DEFAULT
SESSIONS_PER_USER        1
IDLE_TIME                30;
